### ISSUE TITLE
Checking auth

### ISSUE THREAD

**Issue by ACPK** [ianobermiller/nuclearmail#10]
How do you manage the redirect (lightbox in your case) when a user is not authenticated? I saw your comment in regard to the React Starter Kit auth issue.

**Comment by ianobermiller** [comment]
The `AuthorizationReducer` starts with a [default state of `isAuthorized: false`](https://github.com/ianobermiller/nuclearmail/blob/master/src/AuthorizationReducer.js#L6). The `App` component reads the value and [shows the modal if it is false](https://github.com/ianobermiller/nuclearmail/blob/master/src/App.js#L207-L209).
