### ISSUE TITLE
echo Is not an internal or external command, nor a running program or batch file.

### ISSUE THREAD

**Issue by mingtian110** [ianobermiller/nuclearmail#15]
When I try to run the start command it errors out right off the bat with 
         [nodemon] 1.9.2
         [nodemon] to restart at any time, enter `rs`
         [nodemon] watching: index.html
         [nodemon] starting `'echo `cp index.html build/index.html`'`
         **echo Is not an internal or external command, nor a running program or batch file.**(the chinese mean)
         [nodemon] app crashed - waiting for file changes before starting...
![image](https://cloud.githubusercontent.com/assets/11565694/15879991/c84e1df6-2d5b-11e6-85b3-2a18536a7f9b.png)

**Comment by ianobermiller** [comment]
I think @Zipbug ran into this issue in #14 as well. I don't really know what the cause is.

**Comment by Zipbug** [comment]
I did indeed, I had to manually install all the dependencies for some reason and then it started working.

**Comment by mingtian110** [comment]
It seems to be the only way.
