### ISSUE TITLE
Can I use this with greenmail mock SMTP/IMAP server?

### ISSUE THREAD

**Issue by ahmedmohiduet** [ianobermiller/nuclearmail#18]
Hello,

Can I try Nuclearmail with mock SMTP/IMAP server? Would like to implement if this is a new features implentation and send a PR. Let me know how can I configure/codechange Nuclearmail so I could give nuclear UI a try with greenmail(www.icegreen.com/greenmail) mock SMTP server.

**Comment by ianobermiller** [comment]
Probably not. Nuclear Mail is completely built on top of the gmail APIs. That being said if you want to give it a shot, go right ahead :)
