### ISSUE TITLE
Organizing js files

### ISSUE THREAD

**Issue by dqdinh** [ianobermiller/nuclearmail#2]
I was reading through the source and found organizing the js files into directories helpful in understanding the `action -> dispatcher -> store -> view` flux flow.

I organized `src/js/` into the following directories and files.
```console
       src/js/actions/
        src/js/api/
        src/js/components/
        src/js/constants/
        src/js/dispatcher/
        src/js/mixins/
        src/js/stores/
        src/js/utils/
        src/js/main.js
        src/js/routes.js
        src/js/route.js        
```

I can make create PR for this change if it is something you'd like to do.

**Comment by ianobermiller** [comment]
I've avoided putting files into directories for a couple reasons:
1. I hate relative require's. I never want to think about what directory I'm in when I require a file, and I want to be able to move files around however I want without changing their contents.
2. I don't use directory browsers (always just cmd+p in sublime)

I'd be up for moving them into directories if we adopt something like `@providesModule`, which gives every file a unique identifier irrespective of path.

**Comment by dqdinh** [comment]
Sounds good. Thanks for the justification.

**Comment by ianobermiller** [comment]
Thanks for your interest. Something like [commoner](https://github.com/reactjs/commoner) might be nice.
