### ISSUE TITLE
Sign in with google is temporarily disabled

### ISSUE THREAD

**Issue by TedSean** [ianobermiller/nuclearmail#21]
I am getting this on google login.

![image](https://user-images.githubusercontent.com/16174144/76317364-1dd7fc80-6302-11ea-9dd8-428cee31de65.png)

**Comment by ianobermiller** [comment]
It isn't a proper app, so I ca not verify it with Google. You can run it locally with your own Google app authentication credentials. https://support.google.com/cloud/answer/7454865?hl=en
