### ISSUE TITLE
Add Intl polyfill for Safari

### ISSUE THREAD

**Issue by stvchu** [ianobermiller/nuclearmail#3]
I use safari on Mac or iPad to access the demo app, seems it does not work. Pls see screenshot in attachments.
![image](https://cloud.githubusercontent.com/assets/21096/7337893/9c1b0ec8-ec6c-11e4-87bb-0016053a7ce1.jpg)

**Comment by ianobermiller** [comment]
Oh yeah, KP. Need to add a polyfill for Intl, like https://github.com/andyearnshaw/Intl.js. Should only load the polyfill in Safari.
